workflows:
  - name: bazel CI
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - "**"
  - name: gitops
    steps:
      - name: Create gitops PRs
        run: | #multiline command
          ls
